# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and test the Python Package

on:
  push

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gammapy-version: ["1.1", "1.2", "1.3"]
        python-version: ["3.9", "3.11"]
        exclude:
          - gammapy-version: 1.1
            python-version: 3.11
          - gammapy-version: 1.2
            python-version: 3.9
          - gammapy-version: 1.3
            python-version: 3.9

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies, download test data, install package and run test
        run: | 
          python -m pip install --upgrade pip setuptools wheel pytest
          if [ ${{ matrix.gammapy-version }} = "1.1" ]; then python -m pip install astropy==5.3.4 numpy==1.22; else echo "No specific version of astropy and numpy required"; fi
          python -m pip install gammapy==${{ matrix.gammapy-version }}
          git clone --depth 1 --branch v${{ matrix.gammapy-version }} https://github.com/gammapy/gammapy-data
          export GAMMAPY_DATA=$PWD/gammapy-data/
          python -m pip install .
          python -c "import sys; print(\"Python version : \", sys.version)"
          python -c "import gammapy; print(\"gammapy version : \", gammapy.__version__)"
          python -c "import astropy; print(\"astropy version : \", astropy.__version__)"
          python -c "import numpy; print(\"numpy version : \", numpy.__version__)"
          python -c "import scipy; print(\"scipy version : \", scipy.__version__)"
          python -c "import iminuit; print(\"iminuit version : \", iminuit.__version__)"
          pytest
